# Test pipeline

# configure the pipeline
trigger: none
pr:
  - master
pool:
  vmImage: 'ubuntu-latest'


# establish environemnt variables for all stages, jobs, and steps
variables:
  DBT_PROFILE_TARGET: test
  DBT_PROFILE_ROLE:   UPST_FINANCIAL_REPORTING_DBT_TEST_SERVICE_ACCOUNT_ROLE
  DBT_PROFILE_DB:     UPST_FINANCIAL_REPORTING_TEST
  DBT_PROFILE_WH:     UPST_FINANCIAL_REPORTING_DBT_TEST_WH
  TZ:                 America/Chicago


stages:
  - stage: build_and_test
    displayName: Build and test
    jobs:
      - job: run_dbt_tests
        displayName: Run DBT Tests
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.7'
            displayName: 'Install python $(python.version)'

          - script: |
              python -m pip install --upgrade pip
              pip install dbt
            displayName: 'Update PIP and install DBT'

          - script: |
              export DBT_PROFILE_SCHEMA=PR_$(date +"%Y%m%d_%H%M%S_%Z")
              cd dbt
              dbt run --profiles-dir ../azure_pipelines/dbt_pipeline_profiles
              dbt test --profiles-dir ../azure_pipelines/dbt_pipeline_profiles
            displayName: 'Deploy and test with DBT'
            env:
              DBT_PROFILE_SNOWFLAKE_ACCOUNT: $(UPST_FINANCIAL_REPORTING_SNOWFLAKE_ACCOUNT) # Set these values as secrets in the Azure pipelines web UI
              DBT_PROFILE_USER:              $(UPST_FINANCIAL_REPORTING_DBT_TEST_USERNAME) # Set these values as secrets in the Azure pipelines web UI
              DBT_PROFILE_PASSWORD:          $(UPST_FINANCIAL_REPORTING_DBT_TEST_PASSWORD) # Set these values as secrets in the Azure pipelines web UI

            