//=============================================================================
// delete everything in the project
//=============================================================================
USE ROLE SYSADMIN;
DROP DATABASE  UPST_FINANCIAL_REPORTING_DEV;
DROP DATABASE  UPST_FINANCIAL_REPORTING_TEST;
DROP DATABASE  UPST_FINANCIAL_REPORTING_PROD;
DROP WAREHOUSE UPST_FINANCIAL_REPORTING_DBT_TEST_WH;
DROP WAREHOUSE UPST_FINANCIAL_REPORTING_DBT_PROD_WH;
DROP WAREHOUSE UPST_FINANCIAL_REPORTING_POWERBI_ANALYST_WH;
DROP WAREHOUSE UPST_FINANCIAL_REPORTING_TABLEAU_ANALYST_WH;
DROP WAREHOUSE UPST_FINANCIAL_REPORTING_DEVELOPER_WH;

USE ROLE SECURITYADMIN;
DROP ROLE UPST_FINANCIAL_REPORTING_DBT_TEST_WH_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_DBT_TEST_WH_USAGE;
DROP ROLE UPST_FINANCIAL_REPORTING_DBT_TEST_SERVICE_ACCOUNT_ROLE;
DROP ROLE UPST_FINANCIAL_REPORTING_DBT_PROD_WH_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_DBT_PROD_WH_USAGE;
DROP ROLE UPST_FINANCIAL_REPORTING_DBT_PROD_SERVICE_ACCOUNT_ROLE;
DROP ROLE UPST_FINANCIAL_REPORTING_POWERBI_ANALYST_WH_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_POWERBI_ANALYST_WH_USAGE;
DROP ROLE UPST_FINANCIAL_REPORTING_POWERBI_ANALYST;
DROP ROLE UPST_FINANCIAL_REPORTING_TABLEAU_ANALYST_WH_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_TABLEAU_ANALYST_WH_USAGE;
DROP ROLE UPST_FINANCIAL_REPORTING_TABLEAU_ANALYST;
DROP ROLE UPST_FINANCIAL_REPORTING_DEV_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_DEV_WRITE;
DROP ROLE UPST_FINANCIAL_REPORTING_DEV_READ;
DROP ROLE UPST_FINANCIAL_REPORTING_TEST_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_TEST_WRITE;
DROP ROLE UPST_FINANCIAL_REPORTING_TEST_READ;
DROP ROLE UPST_FINANCIAL_REPORTING_PROD_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_PROD_WRITE;
DROP ROLE UPST_FINANCIAL_REPORTING_PROD_READ;
DROP ROLE UPST_FINANCIAL_REPORTING_PROD_ANALYTICS_READ;
DROP ROLE UPST_FINANCIAL_REPORTING_DEVELOPER_WH_OWNER;
DROP ROLE UPST_FINANCIAL_REPORTING_DEVELOPER_WH_ALL_PRIVILEGES;
DROP ROLE UPST_FINANCIAL_REPORTING_ADMIN;
DROP ROLE UPST_FINANCIAL_REPORTING_DEVELOPER;
DROP USER UPST_FINANCIAL_REPORTING_DBT_TEST_SERVICE_ACCOUNT_USER;
DROP USER UPST_FINANCIAL_REPORTING_DBT_PROD_SERVICE_ACCOUNT_USER;
DROP USER UPST_FINANCIAL_REPORTING_POWERBI_ANALYST_SERVICE_ACCOUNT_USER;
DROP USER UPST_FINANCIAL_REPORTING_TABLEAU_ANALYST_SERVICE_ACCOUNT_USER;
//=============================================================================